//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace API_Paycomet_cs.api.paycomet.com_2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PAYTPV_OperationsGatewayBinding", Namespace="urn:PAYTPV_OperationsGateway")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Operation))]
    public partial class PAYTPV_OperationsGatewayService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback search_operationsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PAYTPV_OperationsGatewayService() {
            this.Url = global::API_Paycomet_cs.Properties.Settings.Default.API_Paycomet_cs_api_paycomet_com_2_PAYTPV_OperationsGatewayService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event search_operationsCompletedEventHandler search_operationsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.xmlsoap.org/soap/envelope/#Operations_Engine#search_operations", RequestNamespace="http://schemas.xmlsoap.org/soap/envelope/", ResponseNamespace="http://schemas.xmlsoap.org/soap/envelope/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Operation[] search_operations(
                    string PAYTPV_OPERATIONS_MERCHANTCODE, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string PAYTPV_OPERATIONS_SORTYPE, 
                    string PAYTPV_OPERATIONS_SORTORDER, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string PAYTPV_OPERATIONS_LIMIT, 
                    string[] PAYTPV_OPERATIONS_TERMINAL, 
                    string[] PAYTPV_OPERATIONS_OPERATIONS, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string PAYTPV_OPERATIONS_MINAMOUNT, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string PAYTPV_OPERATIONS_MAXAMOUNT, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string PAYTPV_OPERATIONS_STATE, 
                    string PAYTPV_OPERATIONS_FROMDATE, 
                    string PAYTPV_OPERATIONS_TODATE, 
                    string PAYTPV_OPERATIONS_CURRENCY, 
                    string PAYTPV_OPERATIONS_SIGNATURE, 
                    string PAYTPV_OPERATIONS_REFERENCE, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string PAYTPV_OPERATIONS_SEARCHTYPE, 
                    string PAYTPV_OPERATIONS_VERSION) {
            object[] results = this.Invoke("search_operations", new object[] {
                        PAYTPV_OPERATIONS_MERCHANTCODE,
                        PAYTPV_OPERATIONS_SORTYPE,
                        PAYTPV_OPERATIONS_SORTORDER,
                        PAYTPV_OPERATIONS_LIMIT,
                        PAYTPV_OPERATIONS_TERMINAL,
                        PAYTPV_OPERATIONS_OPERATIONS,
                        PAYTPV_OPERATIONS_MINAMOUNT,
                        PAYTPV_OPERATIONS_MAXAMOUNT,
                        PAYTPV_OPERATIONS_STATE,
                        PAYTPV_OPERATIONS_FROMDATE,
                        PAYTPV_OPERATIONS_TODATE,
                        PAYTPV_OPERATIONS_CURRENCY,
                        PAYTPV_OPERATIONS_SIGNATURE,
                        PAYTPV_OPERATIONS_REFERENCE,
                        PAYTPV_OPERATIONS_SEARCHTYPE,
                        PAYTPV_OPERATIONS_VERSION});
            return ((Operation[])(results[0]));
        }
        
        /// <remarks/>
        public void search_operationsAsync(
                    string PAYTPV_OPERATIONS_MERCHANTCODE, 
                    string PAYTPV_OPERATIONS_SORTYPE, 
                    string PAYTPV_OPERATIONS_SORTORDER, 
                    string PAYTPV_OPERATIONS_LIMIT, 
                    string[] PAYTPV_OPERATIONS_TERMINAL, 
                    string[] PAYTPV_OPERATIONS_OPERATIONS, 
                    string PAYTPV_OPERATIONS_MINAMOUNT, 
                    string PAYTPV_OPERATIONS_MAXAMOUNT, 
                    string PAYTPV_OPERATIONS_STATE, 
                    string PAYTPV_OPERATIONS_FROMDATE, 
                    string PAYTPV_OPERATIONS_TODATE, 
                    string PAYTPV_OPERATIONS_CURRENCY, 
                    string PAYTPV_OPERATIONS_SIGNATURE, 
                    string PAYTPV_OPERATIONS_REFERENCE, 
                    string PAYTPV_OPERATIONS_SEARCHTYPE, 
                    string PAYTPV_OPERATIONS_VERSION) {
            this.search_operationsAsync(PAYTPV_OPERATIONS_MERCHANTCODE, PAYTPV_OPERATIONS_SORTYPE, PAYTPV_OPERATIONS_SORTORDER, PAYTPV_OPERATIONS_LIMIT, PAYTPV_OPERATIONS_TERMINAL, PAYTPV_OPERATIONS_OPERATIONS, PAYTPV_OPERATIONS_MINAMOUNT, PAYTPV_OPERATIONS_MAXAMOUNT, PAYTPV_OPERATIONS_STATE, PAYTPV_OPERATIONS_FROMDATE, PAYTPV_OPERATIONS_TODATE, PAYTPV_OPERATIONS_CURRENCY, PAYTPV_OPERATIONS_SIGNATURE, PAYTPV_OPERATIONS_REFERENCE, PAYTPV_OPERATIONS_SEARCHTYPE, PAYTPV_OPERATIONS_VERSION, null);
        }
        
        /// <remarks/>
        public void search_operationsAsync(
                    string PAYTPV_OPERATIONS_MERCHANTCODE, 
                    string PAYTPV_OPERATIONS_SORTYPE, 
                    string PAYTPV_OPERATIONS_SORTORDER, 
                    string PAYTPV_OPERATIONS_LIMIT, 
                    string[] PAYTPV_OPERATIONS_TERMINAL, 
                    string[] PAYTPV_OPERATIONS_OPERATIONS, 
                    string PAYTPV_OPERATIONS_MINAMOUNT, 
                    string PAYTPV_OPERATIONS_MAXAMOUNT, 
                    string PAYTPV_OPERATIONS_STATE, 
                    string PAYTPV_OPERATIONS_FROMDATE, 
                    string PAYTPV_OPERATIONS_TODATE, 
                    string PAYTPV_OPERATIONS_CURRENCY, 
                    string PAYTPV_OPERATIONS_SIGNATURE, 
                    string PAYTPV_OPERATIONS_REFERENCE, 
                    string PAYTPV_OPERATIONS_SEARCHTYPE, 
                    string PAYTPV_OPERATIONS_VERSION, 
                    object userState) {
            if ((this.search_operationsOperationCompleted == null)) {
                this.search_operationsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_operationsOperationCompleted);
            }
            this.InvokeAsync("search_operations", new object[] {
                        PAYTPV_OPERATIONS_MERCHANTCODE,
                        PAYTPV_OPERATIONS_SORTYPE,
                        PAYTPV_OPERATIONS_SORTORDER,
                        PAYTPV_OPERATIONS_LIMIT,
                        PAYTPV_OPERATIONS_TERMINAL,
                        PAYTPV_OPERATIONS_OPERATIONS,
                        PAYTPV_OPERATIONS_MINAMOUNT,
                        PAYTPV_OPERATIONS_MAXAMOUNT,
                        PAYTPV_OPERATIONS_STATE,
                        PAYTPV_OPERATIONS_FROMDATE,
                        PAYTPV_OPERATIONS_TODATE,
                        PAYTPV_OPERATIONS_CURRENCY,
                        PAYTPV_OPERATIONS_SIGNATURE,
                        PAYTPV_OPERATIONS_REFERENCE,
                        PAYTPV_OPERATIONS_SEARCHTYPE,
                        PAYTPV_OPERATIONS_VERSION}, this.search_operationsOperationCompleted, userState);
        }
        
        private void Onsearch_operationsOperationCompleted(object arg) {
            if ((this.search_operationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_operationsCompleted(this, new search_operationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PAYTPV_OperationsGateway")]
    public partial class Operation {
        
        private string pAYTPV_ERROR_IDField;
        
        private string pAYTPV_OPERATION_IDField;
        
        private string pAYTPV_OPERATION_TIMESTAMPField;
        
        private string pAYTPV_OPERATION_REFERENCEField;
        
        private string pAYTPV_OPERATION_OPERATIONField;
        
        private string pAYTPV_OPERATION_OPERATIONNAMEField;
        
        private string pAYTPV_OPERATION_STATEField;
        
        private string pAYTPV_OPERATION_STATENAMEField;
        
        private string pAYTPV_OPERATION_TERMINALField;
        
        private string pAYTPV_OPERATION_TERMINALNAMEField;
        
        private string pAYTPV_OPERATION_PANField;
        
        private string pAYTPV_OPERATION_USERField;
        
        private string pAYTPV_OPERATION_AMOUNTField;
        
        private string pAYTPV_OPERATION_CURRENCYField;
        
        private string pAYTPV_OPERATION_AMOUNTDISPLAYField;
        
        private string pAYTPV_OPERATION_ERRORIDField;
        
        private string pAYTPV_OPERATION_ERRORDESCField;
        
        private string pAYTPV_OPERATION_FEEEUROField;
        
        private string pAYTPV_OPERATION_FEEPERCENTField;
        
        private string pAYTPV_OPERATION_IPField;
        
        private string pAYTPV_OPERATION_CARDBRANDField;
        
        private string pAYTPV_OPERATION_BICCODEField;
        
        private string pAYTPV_OPERATION_SCORINGField;
        
        private string pAYTPV_OPERATION_AUTHCODEField;
        
        private string pAYTPV_OPERATION_BANKMERCHANTField;
        
        private string pAYTPV_OPERATION_CONCEPTField;
        
        private string pAYTPV_OPERATION_PANCOUNTRYField;
        
        private string pAYTPV_OPERATION_COUNTRYField;
        
        private string pAYTPV_OPERATION_ISSUERBANKField;
        
        private string pAYTPV_OPERATION_SPLITIDField;
        
        private string pAYTPV_OPERATION_METHODIDField;
        
        private string pAYTPV_OPERATION_METHODNAMEField;
        
        /// <remarks/>
        public string PAYTPV_ERROR_ID {
            get {
                return this.pAYTPV_ERROR_IDField;
            }
            set {
                this.pAYTPV_ERROR_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_ID {
            get {
                return this.pAYTPV_OPERATION_IDField;
            }
            set {
                this.pAYTPV_OPERATION_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_TIMESTAMP {
            get {
                return this.pAYTPV_OPERATION_TIMESTAMPField;
            }
            set {
                this.pAYTPV_OPERATION_TIMESTAMPField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_REFERENCE {
            get {
                return this.pAYTPV_OPERATION_REFERENCEField;
            }
            set {
                this.pAYTPV_OPERATION_REFERENCEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_OPERATION {
            get {
                return this.pAYTPV_OPERATION_OPERATIONField;
            }
            set {
                this.pAYTPV_OPERATION_OPERATIONField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_OPERATIONNAME {
            get {
                return this.pAYTPV_OPERATION_OPERATIONNAMEField;
            }
            set {
                this.pAYTPV_OPERATION_OPERATIONNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_STATE {
            get {
                return this.pAYTPV_OPERATION_STATEField;
            }
            set {
                this.pAYTPV_OPERATION_STATEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_STATENAME {
            get {
                return this.pAYTPV_OPERATION_STATENAMEField;
            }
            set {
                this.pAYTPV_OPERATION_STATENAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_TERMINAL {
            get {
                return this.pAYTPV_OPERATION_TERMINALField;
            }
            set {
                this.pAYTPV_OPERATION_TERMINALField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_TERMINALNAME {
            get {
                return this.pAYTPV_OPERATION_TERMINALNAMEField;
            }
            set {
                this.pAYTPV_OPERATION_TERMINALNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_PAN {
            get {
                return this.pAYTPV_OPERATION_PANField;
            }
            set {
                this.pAYTPV_OPERATION_PANField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_USER {
            get {
                return this.pAYTPV_OPERATION_USERField;
            }
            set {
                this.pAYTPV_OPERATION_USERField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_AMOUNT {
            get {
                return this.pAYTPV_OPERATION_AMOUNTField;
            }
            set {
                this.pAYTPV_OPERATION_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_CURRENCY {
            get {
                return this.pAYTPV_OPERATION_CURRENCYField;
            }
            set {
                this.pAYTPV_OPERATION_CURRENCYField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_AMOUNTDISPLAY {
            get {
                return this.pAYTPV_OPERATION_AMOUNTDISPLAYField;
            }
            set {
                this.pAYTPV_OPERATION_AMOUNTDISPLAYField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_ERRORID {
            get {
                return this.pAYTPV_OPERATION_ERRORIDField;
            }
            set {
                this.pAYTPV_OPERATION_ERRORIDField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_ERRORDESC {
            get {
                return this.pAYTPV_OPERATION_ERRORDESCField;
            }
            set {
                this.pAYTPV_OPERATION_ERRORDESCField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_FEEEURO {
            get {
                return this.pAYTPV_OPERATION_FEEEUROField;
            }
            set {
                this.pAYTPV_OPERATION_FEEEUROField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_FEEPERCENT {
            get {
                return this.pAYTPV_OPERATION_FEEPERCENTField;
            }
            set {
                this.pAYTPV_OPERATION_FEEPERCENTField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_IP {
            get {
                return this.pAYTPV_OPERATION_IPField;
            }
            set {
                this.pAYTPV_OPERATION_IPField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_CARDBRAND {
            get {
                return this.pAYTPV_OPERATION_CARDBRANDField;
            }
            set {
                this.pAYTPV_OPERATION_CARDBRANDField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_BICCODE {
            get {
                return this.pAYTPV_OPERATION_BICCODEField;
            }
            set {
                this.pAYTPV_OPERATION_BICCODEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_SCORING {
            get {
                return this.pAYTPV_OPERATION_SCORINGField;
            }
            set {
                this.pAYTPV_OPERATION_SCORINGField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_AUTHCODE {
            get {
                return this.pAYTPV_OPERATION_AUTHCODEField;
            }
            set {
                this.pAYTPV_OPERATION_AUTHCODEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_BANKMERCHANT {
            get {
                return this.pAYTPV_OPERATION_BANKMERCHANTField;
            }
            set {
                this.pAYTPV_OPERATION_BANKMERCHANTField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_CONCEPT {
            get {
                return this.pAYTPV_OPERATION_CONCEPTField;
            }
            set {
                this.pAYTPV_OPERATION_CONCEPTField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_PANCOUNTRY {
            get {
                return this.pAYTPV_OPERATION_PANCOUNTRYField;
            }
            set {
                this.pAYTPV_OPERATION_PANCOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_COUNTRY {
            get {
                return this.pAYTPV_OPERATION_COUNTRYField;
            }
            set {
                this.pAYTPV_OPERATION_COUNTRYField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_ISSUERBANK {
            get {
                return this.pAYTPV_OPERATION_ISSUERBANKField;
            }
            set {
                this.pAYTPV_OPERATION_ISSUERBANKField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_SPLITID {
            get {
                return this.pAYTPV_OPERATION_SPLITIDField;
            }
            set {
                this.pAYTPV_OPERATION_SPLITIDField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_METHODID {
            get {
                return this.pAYTPV_OPERATION_METHODIDField;
            }
            set {
                this.pAYTPV_OPERATION_METHODIDField = value;
            }
        }
        
        /// <remarks/>
        public string PAYTPV_OPERATION_METHODNAME {
            get {
                return this.pAYTPV_OPERATION_METHODNAMEField;
            }
            set {
                this.pAYTPV_OPERATION_METHODNAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void search_operationsCompletedEventHandler(object sender, search_operationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_operationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_operationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Operation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Operation[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591